### PR TITLE
Updated BipartiteMatch to be C++

### PR DESCRIPTION
**Pull request by Diusrex**

### CODE REVIEW

**Comment by dylana37** [comment]
Why do we need to swap C to C++ especially when the size of the file increases? If we're really going to have both why not just keep the C one and add the C++ one in.

**Comment by Diusrex** [comment]
The idea of switching to C++ is to more modernize the repository. The idea with this repo is to store code that people can copy into their solutions for UVa problems, or another website, so it is more important to be readable than be of smaller size. Most of the increase in size, if not all, is for additional comments or breaking statements into multiple lines.

It had been my understanding that we were wanting to remove the old C version, because most people will not be writing it in C. It is fine to keep the C version in, but if we keep both then there will be a lot more files that people will need to scan through to find that they are looking for.

**Comment by dylana37** [comment]
Using C++ blocks people who don't know C++ from using the code archive. This happens to include a decent amount of the 274/275 crowd.

The readability of the code is not really a desired trait. The goal is to have code that's easy to c/p during a contest. Readability is just something that is wanted on the side. I like henry's idea of having two files where one is readable and one is abbreviated.

Plus this is after all an archive. So having a lot of code in it isn't a bad thing. I still believe we should keep both available and let people decide what they want to use.

**Comment by Diusrex** [comment]
I don't think that most people from 274/75 will want to use C for anything past low intermediate level difficulty. For instance, I can't find any easy map container for C, with it and many other vital containers apparently not being in [standard C](http://stackoverflow.com/questions/305611/container-class-library-for-c). This really does limit the usefulness of encouraging them to use C. Even if there is anything in the standard library for it, I can't seem to find anything easily, which would limit how much they would be able do with just C.

For a contest, the readability doesn't matter at all, I agree. Unless the algorithm needs to be adjusted, but that is fairly rare. However, you cannot bring in digital code, it must be printed, so this archive would need to be printed off to be useful. However, I would rather use the world finals pdfs, since they are far more concise anyway. Also, if we are able to copy = paste during a contest, then the length of the file wouldn't matter anyway, since can just copy it all.

Having the readable and abbreviated files is a good idea though. It is fine to have lots of code, so long as having the extra code doesn't make it harder to find what you want.

All this said, I am cancelling this pull request since some of the documentation that was already in the problem is incorrect, mainly how it states that the algorithm is O(N) on the number of elements that there are.

**Pull request closed without merging**
